language: node_js
node_js:
- stable
- iojs
- iojs-v1.0.4
notifications:
  slack:
    secure: eJL7cnwuQXD7hYmCg43PmO/6gVbPM2UhpA41Trml+jDyNGnFHlbUntbg1Uyk7kKSCWKo1ndXVoviLPnciLdf82gSW/bIRcanWA7gLol9LDeCvW2n3PNzh6R2cRC9UzOTIf2E7YN0IQMjwFlEy8CZJKSJDfYzFwXokwK9rbv4V3o=
